language: cpp

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake3 libboost-atomic-dev libboost-chrono-dev libboost-date-time-dev libboost-system-dev libboost-thread-dev
  - curl https://www.openssl.org/source/openssl-1.0.2l.tar.gz | tar xz
  - cd openssl-1.0.2l/
  - ./config shared
  - make
  - sudo make install
  - cd ../

script:
  - mkdir build
  - cd build/
  - cmake -DOPENSSL_ROOT_DIR="/usr/local/ssl/" ..
  - make
  - sudo make install
